return {
    NODE_TYPE = {
        CAPITAL = "CAPITAL",
        OUTPOST = "OUTPOST"
    },

    NODE = {
        PROTECTED = "PROTECTED",
        TARGETABLE = "TARGETABLE",
        UNDER_ATTACK = "UNDER_ATTACK",
        OCCUPIED = "OCCUPIED",
        CONQUERED = "CONQUERED",
        RESTORED = "RESTORED",
        CAPITAL_TARGETABLE = "CAPITAL_TARGETABLE",
        CAPITAL_UNDER_ATTACK = "CAPITAL_UNDER_ATTACK",
        CAPITAL_DEFEATED = "CAPITAL_DEFEATED"
    },

    FLAG = {
        BOUND = "BOUND",
        MISSING = "MISSING"
    },

    CAMPAIGN = {
        ACTIVE = "ACTIVE",
        CEASEFIRE_PAUSED = "CEASEFIRE_PAUSED",
        REARMING = "REARMING",
        PEACE_RESOLVED = "PEACE_RESOLVED",
        CAPITAL_DEFEATED = "CAPITAL_DEFEATED"
    },

    OCCUPATION = {
        OCCUPIED = "OCCUPIED",
        COUNTER_ATTACK = "COUNTER_ATTACK",
        PAUSED = "PAUSED",
        RESTORED = "RESTORED",
        CONQUERED = "CONQUERED"
    },

    LOOT = {
        CREATED = "CREATED",
        IN_TRANSIT = "IN_TRANSIT",
        EXTRACTED = "EXTRACTED",
        RECOVERED = "RECOVERED"
    }
}
