return {
    NEUTRAL = "NEUTRAL",

    WAR_PENDING = "WAR_PENDING",
    WAR = "WAR",

    CEASEFIRE_PENDING = "CEASEFIRE_PENDING",
    CEASEFIRE = "CEASEFIRE",

    PEACE_PENDING = "PEACE_PENDING",

    ALLIANCE_PENDING = "ALLIANCE_PENDING",
    ALLIANCE = "ALLIANCE"
}